language: scala
scala:
  - 2.11.8
jdk: oraclejdk8
sudo: required

cache:
  directories:
    - $HOME/.sbt/boot
    - $HOME/.ivy2/cache

script:
  - sbt clean scalastyle coverage test coverageReport coverageAggregate

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - rav@spotify.com
