language: scala
scala:
  - 2.11.8
jdk: oraclejdk8
sudo: required

cache:
  directories:
    - $HOME/.sbt/boot
    - $HOME/.ivy2/cache

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/.travis/data-integration-test-0acbc82d8523.json

# GCP credentials for integration test
before_install:
  - openssl aes-256-cbc -K $encrypted_b7bb6f667b3b_key -iv $encrypted_b7bb6f667b3b_iv -in .travis/data-integration-test-0acbc82d8523.json.enc -out .travis/data-integration-test-0acbc82d8523.json -d
  - .travis/makeGcpPropertiesFile.sh

script:
  - sbt clean scalastyle coverage test it:test coverageReport coverageAggregate

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - rav@spotify.com
